✨ feat: QuizPage 개발
FG-Academy/FG-Academy-BE pull request #23
Opened 2024-03-28 09:00 UTC by jknadan

### 📟 연결된 이슈
[퀴즈 페이지 개발]
.

### 👷 작업한 내용
- [ ] 코스ID에 따른 모든 강의 정보와 퀴즈 정보를 가져오는 쿼리 수정
- [ ] 퀴즈 모듈 컨트롤러 서비스 생성
- [ ] LectureID에 따른 퀴즈 정보 불러오기 와 퀴즈 제출하기 기능 생성
- [ ] 로그인 기능 보완으로 인한 인증 절차 시 @Public 데코레이터 주석 처리
.

### 📸 스크린샷
![image](https://github.com/FG-Academy/FG-Academy-BE/assets/66247589/df071aad-5930-4713-ae3f-6eca3fdabdf7)

![image](https://github.com/FG-Academy/FG-Academy-BE/assets/66247589/18432c47-53eb-4fe0-839f-97a0b3692d91)

2024-03-28 11:00 UTC, speardragon requested changes
고생하셨슴다

2024-03-28 11:00 UTC, speardragon commented on src/api/courses/courses.controller.ts
> +    @Request() req,
`@Request`써도 똑같긴 한데 `@Req() req: Request`로 통일 시킵시당 (Request는 express로부터 import)

2024-03-28 11:00 UTC, speardragon commented on src/api/quizzes/quizzes.controller.ts
> +    @Request() req,
여기도 마찬가지로 `@Req() req: Request`

2024-03-29 08:37 UTC, jknadan commented
고쳤습니닷 확인 부탁드립니당

2024-03-29 08:40 UTC, speardragon approved these changes

2024-03-29 08:40 UTC, merged